/**:
  ros__parameters:
    ld_velocity_ratio: 0.4
    ld_lateral_error_ratio: 2.3
    ld_curvature_ratio: 4.2
    long_ld_lateral_error_threshold: 2.8
    min_lookahead_distance: 0.85
    max_lookahead_distance: 2.2
    converged_steer_rad: 0.15
    reverse_min_lookahead_distance: 2.4
    prediction_ds: 0.35
    prediction_distance_length: 2.1
    resampling_ds: 0.07
    curvature_calculation_distance: 2.4
    enable_path_smoothing: true
    path_filter_moving_ave_num: 26
